### PR TITLE
api-rpc: Added get_producers and get_producer_schedule api call

### PR DESCRIPTION
**Pull request by regisBafutwabo**
I think they are needed... If there is a better way to get the producers schedule please let me know

### CODE REVIEW

**Comment by terrylks** [comment]
Hi @regisBafutwabo.

Are you going to include @eosio-toppings/api-rpc in your own project?
Adding these two api would help on your project?

**Comment by regisBafutwabo** [comment]
> Hi @regisBafutwabo.
> 
> Are you going to include @eosio-toppings/api-rpc in your own project?
> Adding these two api would help on your project?

Yes, it would help me. I would be grateful if you could add them. If you prefer, I can also add the remaining RPC calls from time to time.
Thank You.

**Comment by terrylks** [comment]
@regisBafutwabo 
I am going to test it with these two Apis. 
And yes, we are glad to have your help ( as well as from EOSIO community ) to making our software better. Please help to add the remaining PRC calls if you could.
We will make a merge on this package after all changed has been made and tested.
Many Thanks!!

**Comment by regisBafutwabo** [comment]
> @regisBafutwabo
> I am going to test it with these two Apis.
> And yes, we are glad to have your help ( as well as from EOSIO community ) to making our software better. Please help to add the remaining PRC calls if you could.
> We will make a merge on this package after all changed has been made and tested.
> Many Thanks!!

Thanks, I will do my best!

**Comment by varshajnagaraja** [comment]
This PR has been merged to develop branch, this functionality will be published in the next release

**Pull request closed without merging**
